### ISSUE TITLE
Add docker support

### ISSUE THREAD

**Issue by ppmadalin** [code-monk08/opentrivia#14]
We should give users possibility to install and use our application through Docker. Also it will help us in our development process to simulate a stage and production workflow.

**Comment by code-monk08** [comment]
will have to read some material on how to add docker support...  currently referring testdriven.io 's [Microservices with Docker, Flask](https://testdriven.io/courses/microservices-with-docker-flask-and-react/)

**Comment by ppmadalin** [comment]
I will do it and I will explain. 😃

**Comment by code-monk08** [comment]
WIP in #20

**Comment by ppmadalin** [comment]
This is done also.
