### ISSUE TITLE
Add CI support

### ISSUE THREAD

**Issue by ppmadalin** [code-monk08/opentrivia#15]
We should enable continues integration using travis.

**Comment by code-monk08** [comment]
On it, adding in support for CI.

**Comment by ppmadalin** [comment]
Great! 

Here is an example of .travis.yml

```
dist: xenial   # required for Python >= 3.7
language: python
python:
    - "3.7"
# command to install dependencies
install:
    - pip install -r requirements.txt

# command to run tests
script:
    - python test_opentrivia.py
```

1. You need to create a file .travis.yml in repository
2. Go to https://travis-ci.org
3. Login with your github account
4. Search for this repository 

And that's all.

Travis will detect automatically the file .travis.yml and it will run the commands within it whenever a merge to master is done. 

Also you can add to README.md the build label. 

Doing this we will ensure that our tests are run and pass whenever we will merge to master.

**Comment by code-monk08** [comment]
I guess once we add docker support, we will need to modify .travis.yml.

**Comment by ppmadalin** [comment]
Great! 👍 

Not necessarily.

Mainly we add docker support for the following reasons:

1. We can simulate and configure a production ready environment.
2. For easy installation. If is there someone who wants to test our application, he can do this very easy with a simple docker command without installing requirements.txt and postgresql locally.

**Comment by code-monk08** [comment]
>     2. For easy installation. If is there someone who wants to test our application, he can do this very easy with a simple docker command without installing requirements.txt and postgresql locally.
Alright.
