### ISSUE TITLE
FlaskAPI and blueprints

### ISSUE THREAD

**Issue by ppmadalin** [code-monk08/opentrivia#17]
Hi Guys, 

I have looked a little bit over http://www.flaskapi.org/ and as per my understanding, at this time doesn't not supporting blueprints. 

Not sure if we really need this but I was thinking that maybe in the future we will need to have a more modular way to define our api endpoints. 

Maybe we should go with https://flask-restful.readthedocs.io/en/latest/. What do you say?

Thanks

@bbelderbos @code-monk08

**Comment by code-monk08** [comment]
I am okay with whatever gives us the best compatibility over time.. Flask-Restful +1

**Comment by ppmadalin** [comment]
I will make prototip and I will wait for your feedback after.

**Comment by code-monk08** [comment]
Flask-RESTful has a good documentation and it is making things relatively easier, let's go with it.
