### ISSUE TITLE
Create a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by ppmadalin** [code-monk08/opentrivia#2]
We need to have a proper contribution file. The file should contains simple steps with instructions about setting up the project and how to contribute. 

This will make the project look friendly and to invite future contributors to bring their ideas into this project.

With this project I would like also to target the new pythonists who want to have a first contributions in the open source world. Therefore, a clear contribution file, is a must.

**Comment by code-monk08** [comment]
Fixed in #6 , closing.
