### ISSUE TITLE
API Functionalities & Endpoints

### ISSUE THREAD

**Issue by code-monk08** [code-monk08/opentrivia#22]
- [x] Add a question 
- [x] Add answer(s) to a question
- [x] Update a question
- [x] Update answer(s)
- [x] Delete a question (along with its answers)
- [x] Delete an answer
- [x] Get question(s)
- [x] Get all question(s) & their answer(s)
- [x] Get question category
- [x] Get question level (easy | medium | hard )
- [x] Get type of question (MCQ | T/F)

feel free to add more functionalities
endpoint url structure:  **/api/v1/. . .**

**Comment by espatatis** [comment]
I'd like to work on this.

**Comment by code-monk08** [comment]
@espatatis for starters if you can think of some more endpoints & functionalities which we can add in opentrivia, please feel free to suggest.

**Comment by ppmadalin** [comment]
I think we can close this issue. Endpoints are added and I have created separate issues for their implementation.
