### ISSUE TITLE
Home page and Slack Authentication

### ISSUE THREAD

**Issue by ppmadalin** [code-monk08/opentrivia#29]
Implement Slack Authentication and add more details to home page

**Comment by code-monk08** [comment]
I wonder how we are going to use that?

what I have been thinking is once we are done with our API we will have to add API authentication in it, then any client application such as quiz web app or slack bot, telegram bot etc authenticates with our api and then uses it for creating interactive quizes, what do you say?

**Comment by ppmadalin** [comment]
We will have a home page with different authentication buttons. We will start first with slack and then we can add more applications support. 

In order to do that we will need: 

- our Application to be up and running
- to create a slack Application and make it installable within any Workspace.

**Comment by code-monk08** [comment]
something like

Sign up/ Login as a Contributor?
Sign up/ Login as an Admin?

**Comment by ppmadalin** [comment]
Yep. Something like this.

**Comment by ppmadalin** [comment]
That means we don't even need to create resources through REST API. At least at this time. 
We can just expose questions and answers through API and the creation and manage of those to be through an admin interface.

What you say?

**Comment by ppmadalin** [comment]
We will have a home page with different authentication buttons. We will start first with slack and then we can add more applications support. 

In order to do that we will need: 

- our Application to ne up and running

**Comment by code-monk08** [comment]
> We can just expose questions and answers through API and the creation and manage of them to be through an admin interface.
> 
> What you say?

I agree we can do as stated above.
