### ISSUE TITLE
Implement tests for Endpoints

### ISSUE THREAD

**Issue by ppmadalin** [code-monk08/opentrivia#40]

**Comment by code-monk08** [comment]
a checklist?

- [ ] TEST: Add a question
- [ ] TEST: Add answer(s) to a question
- [ ] TEST: Update a question
- [ ] TEST: Update answer(s)
- [ ] TEST: Delete a question (along with its answers)
- [ ] TEST: Delete an answer
- [ ] TEST: Get question(s)
- [ ] TEST: Get all question(s) & their answer(s)
- [ ] TEST: Get question category
- [ ] TEST: Get question level (easy | medium | hard )
- [ ] TEST: Get type of question (MCQ | T/F)

**Comment by ppmadalin** [comment]
Perfect! Thanks. 😄
