### ISSUE TITLE
Update CONTRIBUTING.md file

### ISSUE THREAD

**Issue by ppmadalin** [code-monk08/opentrivia#43]
Need to add the following to CONTRIBUTING.md file.

1. Create a new issue and tell us about the changes you want to do.
2. Do the changes
3. Create a PR 
4. Link the issue to PR eg: Resolve #<issue_number>

**Comment by code-monk08** [comment]
We already added guideline for the same in our README 
![image](https://user-images.githubusercontent.com/19390263/66254367-e71a1b00-e792-11e9-88b7-aef060393475.png)

**Comment by ppmadalin** [comment]
Right. Sorry.
