### ISSUE TITLE
Branch protection rule

### ISSUE THREAD

**Issue by ppmadalin** [code-monk08/opentrivia#7]
If it is not done already, I think we need to have some rules for master branch and commits. 🤔  

More details can be found at: https://help.github.com/en/articles/configuring-protected-branches

**Comment by code-monk08** [comment]
@ppmadalin thank you for suggesting, I am new to this feature.
what I understand after reading more details is as follows:
-

**Comment by code-monk08** [comment]
@ppmadalin thank you for suggesting, I am new to this feature.
what I understand after reading more details is as follows:

- once I protect master branch, all the collaborators who were invited to this project can not force push their changes to master branch.
- To push their change they will need to open a PR.

Please correct me If I am wrong somewhere.

**Comment by ppmadalin** [comment]
Yep. That's right. 😃

**Comment by code-monk08** [comment]
I have enabled this rule in master branch.
