### ISSUE TITLE
Should we use a code formatter for a better code style consistency?

### ISSUE THREAD

**Issue by ppmadalin** [code-monk08/opentrivia#8]
Within the README file, section Guide Line, I am thinking to add more details regarding code style and how we can keep a consistency of style across entire project. 

Also, I would like to propose to use _black_. It is easy to use and can be configured easily within many IDEs or text editors. 

More details about _black_ can be found at this link: https://github.com/psf/black

Thanks 😃

**Comment by code-monk08** [comment]
Awesome, even I was thinking to have consistent code format over this project's life cycle, **black** is known to me and It's an amazing tool.. I think we can go with it..Thanks. I look forward to your PR.
